server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: http://localhost:9092
    admin:
      auto-create: true
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
